{
 "title": "Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "timeRange",
    "label": "Time Range",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Monitoring Application Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version Matrix",
   "type": "table",
   "description": "Currently deployed service versions.",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(prometheus_build_info) by (container,version,goversion,pod,namespace) or sum(alertmanager_build_info) by (container,version,goversion,pod,namespace) or sum(grafana_build_info) by (container,version,goversion,pod,namespace)"
    }
   ]
  },
  {
   "title": "Total Notification Sent [Time Range]",
   "type": "graph",
   "description": "No. of notifications sent in specified time range.",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{integration=~\"email|slack|webhook|pagerduty\"}[${timeRange}])) by (integration)",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Prometheus - Status",
   "type": "stat",
   "description": "Status:\n\nActive == (❤️)\n\nDown  == (💔)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*-prometheus\"}"
    }
   ]
  },
  {
   "title": "Alertmanager - Status",
   "type": "stat",
   "description": "Status:\n\nActive == (❤️)\n\nDown  == (💔)",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*-alertmanager\"}"
    }
   ]
  },
  {
   "title": "Prometheus <--> Alertmanager",
   "type": "stat",
   "description": "Connection between Prometheus and Alertmanager.\n\nActive == (👍)\n\nDown  == (👎)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered"
    }
   ]
  },
  {
   "title": "Rule evaluation failures [5m]",
   "type": "stat",
   "description": "Prometheus - Number of times rule evaluation failed in last 5m.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total[5m]))"
    }
   ]
  },
  {
   "title": "Prometheus restarts [15m]",
   "type": "stat",
   "description": "Prometheus restarts in last 15m.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{job=~\".*-prometheus\"}[15m])"
    }
   ]
  },
  {
   "title": "Alertmanager restarts [15m]",
   "type": "stat",
   "description": "Alertmanager restart in last 15m.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{job=~\".*-alertmanager\"}[15m])"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "stat",
   "description": "Prometheus - no. of notifications currently in queue.\n\nHigher queue length == Higher notification latency (Not Good)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_queue_length"
    }
   ]
  },
  {
   "title": "Queue capacity",
   "type": "stat",
   "description": "Prometheus - notifications queue size",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_queue_capacity"
    }
   ]
  },
  {
   "title": "Targets - Total",
   "type": "stat",
   "description": "Total targets from which Prometheus is scraping metrics.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Targets - Up",
   "type": "stat",
   "description": "Targets which are up and actively monitored.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up==1)" }
   ]
  },
  {
   "title": "Targets - Down",
   "type": "stat",
   "description": "Targets which are not reachable.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 0)" }
   ]
  },
  {
   "title": "Failed notification [24h]",
   "type": "stat",
   "description": "Alertmanager - Failed email notifications in last 24h.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{integration=\"email\"}[24h]))"
    }
   ]
  },
  { "title": "Alerts Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "All active alerts detected by monitoring system.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ALERTS) or vector(0)" }
   ]
  },
  {
   "title": "Firing",
   "type": "stat",
   "description": "All alerts for which notification has been already sent or will be sent in next few seconds. ",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "description": "All alerts which are active but still in evaluation state.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "description": "All alerts with severity == Critical. These alerts have high priority and require quick response.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{severity=\"critical\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "description": "All alerts with severity == Warning. Such alerts detect issues in their early stages and sometimes only for information purpose.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{severity=\"warning\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "description": "All alerts with severity == Info. Such alerts are only for information purpose. Ex. - DeadManSwitch.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{severity=\"info\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Silenced",
   "type": "stat",
   "description": "All active alerts for which notification has been disabled by someone manually. May be for maintenance purposes.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_silences{state=\"active\"}"
    }
   ]
  },
  {
   "title": "Suppressed",
   "type": "stat",
   "description": "All alerts that are in supressed state as per the conditions defined in inhibition rules.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_alerts{state=\"suppressed\"}"
    }
   ]
  },
  { "title": "Alerts List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Active alert(s) list",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "sort(ALERTS)" }
   ]
  }
 ]
}