{
 "title": "Kafka Consumer Group Lag and Throughput",
 "description": "Kafka consumer group lag and throughput",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kafka_consumergroup_current_offset)"
    }
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{namespace=\"$kubernetes_namespace\",consumergroup!~\".*migration-(tool|validation)-backup.*|.*-gradebook-notifier-.*|.*topics.status.*|.*-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\"}, consumergroup)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{namespace=\"$kubernetes_namespace\", consumergroup=~\"$consumergroup\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Messages consumed per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=~\"$consumergroup\",topic=~\"$topic\"}[10m])/600) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"$topic\"}[10m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}