{
 "title": "Kafka Exporter-Main",
 "description": "Kafka topics and consumer groups",
 "tags": [
  "Kafka",
  "Kafka Exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kafka_consumergroup_current_offset)"
    }
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{namespace=\"$kubernetes_namespace\"}, consumergroup)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{namespace=\"$kubernetes_namespace\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions at mininimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions under mininimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions not on preferred node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader_is_preferred{topic=~\"$topic\"}<1)"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"$topic\"}[10m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages consumed per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=~\"$consumergroup\",topic=~\"$topic\"}[10m])/60) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Group Offsets",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"$consumergroup\",topic=~\"$topic\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Partitions",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}