{
 "title": "kubernetes / pods-by-namespace",
 "tags": [
  "kubernetes",
  "pods",
  "namespace"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "description": "Total CPU requests for all workloads in namespace",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "singlestat",
   "description": "Total CPU limits for all workloads in namespace",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Utilisation % (from requests)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",container!~\"\",container!~\"POD\",image!~\"\"}[1m])) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Utilisation % (from limits)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",container!~\"\",container!~\"POD\",image!~\"\"}[1m])) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "description": "Total memory requests defined for all workloads in the namespace",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "singlestat",
   "description": "Total memory requests defined for all workloads in the namespace",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization % (from requests)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",container!~\"\",container!~\"POD\",image!~\"\"}) / sum(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation % (from limits)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"})"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",container!~\"\",container!~\"POD\",image!~\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace\",type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace\",type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",container!~\"\",container!~\"POD\",image!~\"\"}[1m])) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",container!~\"\",container!~\"POD\",image!~\"\"}[1m])) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",container!~\"\",container!~\"POD\",image!~\"\"}[1m])) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",container!=\"\",image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace\",type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace\",type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",container!=\"\",image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",container!=\"\",image!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",container!=\"\",image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{cluster=~\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{cluster=~\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (pod)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}