{
 "title": "kubernetes / cluster",
 "tags": [
  "kubernetes",
  "cluster"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Headlines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kubernetes Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kubernetes_build_info{cluster=~\"$cluster\",service=\"kubernetes\"}"
    }
   ]
  },
  {
   "title": "Total CPU (cores)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=~\"$cluster\",mode!=\"idle\"}[3m])) / sum(machine_cpu_cores{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Request Commitment (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"core\"}) / sum(machine_cpu_cores{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limit Commitment (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"core\"}) / sum(machine_cpu_cores{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "# Of Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "# Of Nodes (CPU)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(machine_cpu_cores{cluster=~\"$cluster\"} <= 2)",
     "legendFormat": "0-2 (Cores)"
    },
    {
     "expr": "count((machine_cpu_cores{cluster=~\"$cluster\"} > 2) and (machine_cpu_cores{cluster=~\"$cluster\"} <= 4))",
     "legendFormat": "2-4 (Cores)"
    },
    {
     "expr": "count((machine_cpu_cores{cluster=~\"$cluster\"} > 4) and (machine_cpu_cores{cluster=~\"$cluster\"} <= 8))",
     "legendFormat": "4-8 (Cores)"
    },
    {
     "expr": "count((machine_cpu_cores{cluster=~\"$cluster\"} > 8) and (machine_cpu_cores{cluster=~\"$cluster\"} <= 16))",
     "legendFormat": "8-16 (Cores)"
    },
    {
     "expr": "count((machine_cpu_cores{cluster=~\"$cluster\"} > 16) and (machine_cpu_cores{cluster=~\"$cluster\"} <= 32))",
     "legendFormat": "16-32 (Cores)"
    },
    {
     "expr": "count(machine_cpu_cores{cluster=~\"$cluster\"} > 32)",
     "legendFormat": "32+ (Cores)"
    }
   ]
  },
  {
   "title": "# Of Nodes (Memory)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 <= 2)",
     "legendFormat": "0-2 (GB)"
    },
    {
     "expr": "count((node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 > 2) and (node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 <= 4))",
     "legendFormat": "2-4 (GB)"
    },
    {
     "expr": "count((node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 > 4) and (node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 <= 8))",
     "legendFormat": "4-8 (GB)"
    },
    {
     "expr": "count((node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 > 8) and (node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 <= 16))",
     "legendFormat": "8-16 (GB)"
    },
    {
     "expr": "count((node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 > 16) and (node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 <= 32))",
     "legendFormat": "16-32 (GB)"
    },
    {
     "expr": "count(node_memory_MemTotal_bytes{cluster=~\"$cluster\"}/1024/1024/1024 > 32)",
     "legendFormat": "32+ (GB)"
    }
   ]
  },
  {
   "title": "Total Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemFree_bytes{cluster=~\"$cluster\"}) + sum(node_memory_Cached_bytes{cluster=~\"$cluster\"}) + sum(node_memory_Buffers_bytes{cluster=~\"$cluster\"})) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Memory Request Commitment (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"byte\"}) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limit Commitment (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"byte\"}) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "# Of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!~\"\",container!~\"POD\",image!~\"\"}[3m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Pie)",
   "type": "piechart",
   "description": "It shows average CPU utilisation by each namespace within selected time range in dashboard",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!~\"\",container!~\"POD\",image!~\"\"}[3m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Quotas By Namespace",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_owner{cluster=~\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace!~\"\"}[3m])) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"core\"}) by (namespace)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!~\"\",container!~\"POD\",image!~\"\"}[3m])) by (namespace) / sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"core\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"core\"}) by (namespace)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!~\"\",container!~\"POD\",image!~\"\"}[3m])) by (namespace) / sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"core\"}) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\",container!=\"\",namespace!~\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Pie)",
   "type": "piechart",
   "description": "It shows average Memory utilisation by each namespace within selected time range in dashboard ",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory By Namespace",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_owner{cluster=~\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{cluster=~\"$cluster\", container!=\"\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"byte\"}) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{cluster=~\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",unit=\"byte\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"byte\"}) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{cluster=~\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",unit=\"byte\"}) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Network Usage",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace: Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace: Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}