{
 "title": "kubernetes / cronjob",
 "tags": [
  "kubernetes",
  "cronjobs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "cronjob",
    "label": "CronJob",
    "query": {
     "query": "label_values(kube_cronjob_info{cluster=\"$cluster\",namespace=\"$namespace\"}, cronjob)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CronJobs snapshot (All namespaces)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total Cronjobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Cronjobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_status_active{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Suspended Cronjobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_spec_suspend{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Successful vs Failed Jobs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_succeeded{cluster=~\"$cluster\"} == 1) OR on() vector(0)",
     "legendFormat": "Successful Jobs"
    },
    {
     "expr": "count(kube_job_failed{cluster=~\"$cluster\"} == 1) OR on() vector(0)",
     "legendFormat": "Failed Jobs"
    }
   ]
  },
  { "title": "Cronjob details : ${cronjob}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "cronjob" },
  {
   "title": "Schedule",
   "type": "table",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_info{cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"}) by (cronjob,namespace,schedule,concurrency_policy)"
    },
    {
     "expr": "sum(kube_cronjob_spec_starting_deadline_seconds{cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"}) by (cronjob,namespace)"
    }
   ]
  },
  {
   "title": "Successful vs Failed Jobs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (owner_name)(kube_job_complete{cluster=~\"$cluster\",condition=\"true\",namespace=\"$namespace\"} * on (job_name) group_left(owner_name) (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))) OR on() vector(0)",
     "legendFormat": "Successful Jobs"
    },
    {
     "expr": "sum by (owner_name)\n(\n  kube_job_failed{cluster=~\"$cluster\",condition=\"true\",namespace=\"$namespace\"} * on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n  \n) OR on() vector(0) ",
     "legendFormat": "Failed Jobs"
    }
   ]
  },
  {
   "title": "Maximum Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (owner_name)\n(\n  max by(job_name )\n   (\n     kube_job_status_completion_time{cluster=~\"$cluster\",namespace=\"$namespace\"} - on (job_name)\n       kube_job_status_start_time{cluster=~\"$cluster\",namespace=\"$namespace\"} \n   ) * on (job_name)\n    group_left(owner_name)\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n)"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (owner_name)\n(\n  max by(job_name )\n   (\n     kube_job_status_completion_time{cluster=~\"$cluster\",namespace=\"$namespace\"} - on (job_name)\n       kube_job_status_start_time{cluster=~\"$cluster\",namespace=\"$namespace\"} \n   ) * on (job_name)\n    group_left(owner_name)\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n)"
    }
   ]
  },
  {
   "title": "Minimum Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (\n  (kube_job_status_completion_time{cluster=~\"$cluster\",namespace=\"$namespace\"}\n  - on (job_name)\n    kube_job_status_start_time{cluster=~\"$cluster\",namespace=\"$namespace\"})\n  * on (job_name)\n    group_left(owner_name)\n      (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n)"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (owner_name)\n(\n  kube_job_status_active{cluster=~\"$cluster\",namespace=\"$namespace\"} * on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n  \n) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Suspended",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_spec_suspend{cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  }
 ]
}