{
 "title": "kubernetes / nodes",
 "description": "Information of individual kubernetes nodes",
 "tags": [
  "kubernetes",
  "nodes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kubelet_node_name{job=\"kubelet\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{cluster=~\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", node=~\"$node\"}) OR sum(kubelet_running_pod_count{cluster=~\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{cluster=~\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", node=~\"$node\"}) OR sum(kubelet_running_container_count{cluster=~\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Desired Volume Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", node=~\"$node\", state=\"desired_state_of_world\"})"
    }
   ]
  },
  {
   "title": "Actual Volume Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", node=~\"$node\", state=\"actual_state_of_world\"})"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Node info",
   "type": "table",
   "description": "General information about node",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "group by (node,container_runtime_version,kernel_version,kubelet_version,kubeproxy_version,os_image) (kube_node_info{job=\"kube-state-metrics\",cluster=~\"$cluster\",node=~\"$node\"})"
    },
    {
     "expr": "group by (node,instance,version) (node_exporter_build_info{job=\"node-exporter\",cluster=~\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", cluster=~\"$cluster\", mode=\"idle\", node=\"$node\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", cluster=~\"$cluster\", mode=\"idle\", node=\"$node\"})\n)\n",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}",
     "legendFormat": "memory free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"}",
     "legendFormat": "memory total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"})\n/\n  avg(node_memory_MemTotal_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\"})\n* 100\n)\n"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$__interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", fstype!=\"\"}\n  -\n    node_filesystem_avail_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", cluster=~\"$cluster\", node=\"$node\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Pods running on this node",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\",node=\"$node\"}) by (created_by_kind,created_by_name,namespace,pod,pod_ip)"
    }
   ]
  }
 ]
}