{
 "title": "prometheus / alerts",
 "tags": [
  "alerts",
  "kubernetes",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "timeRange",
    "label": "Time Range",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Monitoring Application Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version Matrix",
     "type": "table",
     "description": "Currently deployed service versions.",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(prometheus_build_info{cluster=~\"$cluster\"}) by (container,version,goversion,pod,namespace) or sum(alertmanager_build_info{cluster=~\"$cluster\"}) by (container,version,goversion,pod,namespace) or sum(grafana_build_info{cluster=~\"$cluster\"}) by (container,version,goversion,pod,namespace) or sum(prometheus_operator_build_info{cluster=~\"$cluster\"}) by (container,version,goversion,pod,namespace) or sum(node_exporter_build_info{cluster=~\"$cluster\"}) by (container,version,goversion,namespace)"
      }
     ]
    },
    {
     "title": "Total Notification Sent [Time Range]",
     "type": "graph",
     "description": "No. of notifications sent in specified time range.",
     "gridPos": { "h": 13, "w": 9, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(alertmanager_notifications_total{cluster=~\"$cluster\",integration=~\"email|slack|webhook|pagerduty\"}[${timeRange}])) by (integration)",
       "legendFormat": "{{integration}}"
      }
     ]
    },
    {
     "title": "Prometheus",
     "type": "stat",
     "description": "Status:\n\nActive == (❤️)\n\nDown  == (💔)",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{cluster=~\"$cluster\",job=~\".*-prometheus\"}"
      }
     ]
    },
    {
     "title": "Alertmanager",
     "type": "stat",
     "description": "Status:\n\nActive == (❤️)\n\nDown  == (💔)",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{cluster=~\"$cluster\",job=~\".*-alertmanager\"}"
      }
     ]
    },
    {
     "title": "Prometheus <--> Alertmanager",
     "type": "stat",
     "description": "Connection between Prometheus and Alertmanager.\n\nActive == (👍)\n\nDown  == (👎)",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_notifications_alertmanagers_discovered{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Rule evaluation failures [5m]",
     "type": "stat",
     "description": "Prometheus - Number of times rule evaluation failed in last 5m.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_rule_evaluation_failures_total{cluster=~\"$cluster\"}[5m]))"
      }
     ]
    },
    {
     "title": "Failed notification [24h]",
     "type": "stat",
     "description": "Alertmanager - Failed email notifications in last 24h.",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_notifications_failed_total{cluster=~\"$cluster\",integration=\"email\"}[24h]))"
      }
     ]
    },
    {
     "title": "Targets - Total",
     "type": "stat",
     "description": "Total targets from which Prometheus is scraping metrics.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Targets - Up",
     "type": "stat",
     "description": "Targets which are up and actively monitored.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{cluster=~\"$cluster\"} == 1)"
      }
     ]
    },
    {
     "title": "Targets - Down",
     "type": "stat",
     "description": "Targets which are not reachable.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{cluster=~\"$cluster\"} == 0) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Queue capacity",
     "type": "stat",
     "description": "Prometheus - notifications queue size",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_notifications_queue_capacity{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Queue length",
     "type": "stat",
     "description": "Prometheus - no. of notifications currently in queue.\n\nHigher queue length == Higher notification latency (Not Good)",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_notifications_queue_length{cluster=~\"$cluster\"}"
      }
     ]
    }
   ]
  },
  { "title": "Alerts Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "All active alerts detected by monitoring system.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Firing",
   "type": "stat",
   "description": "All alerts for which notification has been already sent or will be sent in next few seconds. ",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster=~\"$cluster\",alertstate=\"firing\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "description": "All alerts which are active but still in evaluation state.",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster=~\"$cluster\",alertstate=\"pending\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "description": "All alerts with severity == Critical. These alerts have high priority and require quick response.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster=~\"$cluster\",severity=\"critical\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "description": "All alerts with severity == Warning. Such alerts detect issues in their early stages and sometimes only for information purpose.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster=~\"$cluster\",severity=\"warning\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "description": "All alerts with severity == Info. Such alerts are only for information purpose and generally dont require any manual intervention",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster=~\"$cluster\",severity=\"info\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Silences - AlertManager",
   "type": "stat",
   "description": "All active alerts for which notification has been disabled by someone manually in alertmanager, may be for maintenance purposes.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_silences{cluster=~\"$cluster\",state=\"active\"}"
    }
   ]
  },
  { "title": "Alerts (Category)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Alerts By Category",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{cluster=~\"$cluster\"}) by (alertname) OR on() vector(0)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  { "title": "Alerts - Active / Firing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Firing alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sort(ALERTS{cluster=~\"$cluster\",alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Alerts - Pending",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending alerts",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sort(ALERTS{cluster=~\"$cluster\",alertstate=\"pending\"})"
      }
     ]
    }
   ]
  }
 ]
}