{
 "title": "Valamis UI containers-ByService",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(cpu{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cpu{namespace=\"$namespace\", service=~\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cpu{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}) by (service) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(memory{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}) by (service)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "loop_delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(loop_delay{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}) by (service)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "heap_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heap_size{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}) by (service)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "loop_delay_p95",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(loop_delay_p95{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}) by (service)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "used_heap_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (used_heap_size{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}) by (service)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}