apiVersion: v2
appVersion: "1.0.0"
description: "Prometheus - Monitoring tool for Kubernetes"
name: prometheus
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: ~12.8.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: global.kube-prometheus-stack.enabled
  - name: ambassador
    version: ~6.5.0
    repository: "https://www.getambassador.io"
    condition: global.ambassador.enabled
  - name: prometheus-elasticsearch-exporter
    version: ~4.0.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: global.prometheus-elasticsearch-exporter.enabled
