apiVersion: v2
appVersion: "3.0.0"
description: "Prometheus - Monitoring tool for Kubernetes"
name: prometheus
version: 3.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 32.2.1
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: global.kube-prometheus-stack.enabled
  - name: emissary-ingress
    version: 7.3.0
    repository: "https://www.getambassador.io"
    condition: global.emissary-ingress.enabled
  - name: prometheus-elasticsearch-exporter
    version: 4.3.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: global.prometheus-elasticsearch-exporter.enabled
