apiVersion: v2
appVersion: "4.0.0"
description: "Prometheus - Monitoring tool for Kubernetes"
name: prometheus
version: 4.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 36.2.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: global.kube-prometheus-stack.enabled
  - name: emissary-ingress
    version: 7.4.1
    repository: "https://www.getambassador.io"
    condition: global.emissary-ingress.enabled
  - name: prometheus-elasticsearch-exporter
    version: 4.13.0
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: global.prometheus-elasticsearch-exporter.enabled
