---

global:
  grafanaAdminPassword: change-me-length-min-12
  externalDomain: "xyz.abc.com"
  smtpApiKey: change-me
  smtpDestinationAddress: "change-me"
  web:
    ssl:
      externalSecret:
        enabled: true
        keyVaultName: "change-me"

emissary-ingress:
  service:
    type: "LoadBalancer"
    loadBalancerIP: "0.0.0.0"

kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      externalUrl: "http://change-me/alertmanager"
  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: "change-me"
