---

global:
  platform: "azure"
  ambassador:
    enabled: true
  kube-prometheus-stack:
    enabled: true
  prometheus-elasticsearch-exporter:
    enabled: true
  grafanaAdminPassword: change-me-length-min-12
  externalUrl: "xyz.abc.com"
  smtpApiKey: change-me
  smtpDestinationAddress: "change-me"
  web:
    ssl:
      enabled: true
      letsencrypt:
        enabled: false
        certManagerApiMigration: true
      externalSecret:
        enabled: false
        keyVaultName: "change-me"

ambassador:
  service:
    type: "LoadBalancer"
    loadBalancerIP: "0.0.0.0"

prometheus-elasticsearch-exporter:
  es:
    uri: 'http://aux-elasticsearch-master.shared.svc.cluster.local:9200'

kube-prometheus-stack:
  alertmanager:
    enabled: true
    alertmanagerSpec:
      externalUrl: "http://change-me/alertmanager"
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "managed-premium"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
  grafana:
    persistence:
      size: 10Gi
      storageClassName: "managed-premium"
    env:
      GF_SMTP_ENABLED: "true"
  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: "change-me"
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "managed-premium"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
