---

global:
  ambassador:
    enabled: true 
  kube-prometheus-stack:
    enabled: true
  prometheus-elasticsearch-exporter:
    enabled: false 
  externalUrl: "ENV.monitor.valamis.io"
  smtpApiKey: "SENDGRID_API_KEY"
  smtpDestinationAddress: "navodit.sharma@valamis.com"
  web:
    ssl:
      enabled: true 
      letsencrypt:
        enabled: true 
        certManagerApiMigration: true
      externalSecret: 
        enabled: false
        keyVaultName: "CHANGE_ME"

ambassador:
  service:
    loadBalancerIP: "LOAD_BALANCER_IP"

prometheus-elasticsearch-exporter:
  es:
    uri: 'http://aux-elasticsearch-master.shared.svc.cluster.local:9200'

kube-prometheus-stack: 
  alertmanager:
    enabled: true
    alertmanagerSpec:
      externalUrl: "http://sandbox.monitor.valamis.io/alertmanager"
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "managed-premium"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
  grafana:
    persistence:
      size: 10Gi
      storageClassName: "managed-premium"
    env: 
      GF_SECURITY_ADMIN_PASSWORD: "GF_ADMIN_PASSWORD"
      GF_SMTP_ENABLED: "true"
  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: "MC_ValamisSandbox_v4-sandbox-aks_westeurope"
      storageSpec:      
        volumeClaimTemplate:
          spec:
            storageClassName: "managed-premium"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
