groups:
- name: k8s-job-cronjob.rules
  rules:
  - alert: KubernetesJobFailed
    expr: kube_job_status_failed > 0
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Kubernetes Job failed
      description: "Job {{$labels.namespace}}/{{$labels.job_name}} failed to complete."
  # - alert: KubernetesCronjobSuspended
  #   expr: kube_cronjob_spec_suspend != 0
  #   for: 0m
  #   labels:
  #     severity: warning
  #   annotations:
  #     summary: Kubernetes CronJob suspended
  #     description: "CronJob {{ $labels.namespace }}/{{ $labels.cronjob }} is suspended."
  - alert: KubernetesCronjobTooLong
    expr: time() - kube_cronjob_next_schedule_time > 18000
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Kubernetes CronJob too long
      description: "CronJob {{ $labels.namespace }}/{{ $labels.cronjob }} is taking more than 6h to complete."
  - alert: KubernetesJobSlowCompletion
    expr: kube_job_spec_completions - kube_job_status_succeeded > 0
    for: 12h
    labels:
      severity: critical
    annotations:
      summary: Kubernetes job slow completion
      description: "Kubernetes Job {{ $labels.namespace }}/{{ $labels.job_name }} did not complete for last 12h."
