groups:
- name: k8s-replicaset.rules
  rules:
  - alert: KubernetesReplicassetMismatch
    expr: kube_replicaset_spec_replicas != kube_replicaset_status_ready_replicas
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: Kubernetes ReplicasSet mismatch
      description: "Number of ready replicas for replicaset {{ $labels.replicaset }} does not match the desired number of replicas for last 10m."
      value: '{{ printf "%.2f" $value }}'
