{{- if (index $.Values.global "emissary-ingress" "enabled") -}}
apiVersion: getambassador.io/v2
kind: Module
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: "ambassador"
  namespace: "{{ .Release.Namespace }}"
spec:
  #ambassador_id: [ "ambassador1" ]
  config:
  {{- (index $.Values "emissary-ingress" "customModule" "config" "custom") | nindent 4 }}
  {{- if (index $.Values "emissary-ingress" "customModule" "ipWhitelist" "enabled") -}}
  {{- (index $.Values "emissary-ingress" "customModule" "config" "ipWhitelist") | nindent 4 }}
  {{- end -}}
{{- end -}}
