{{- if $.Values.global.ambassador.enabled -}}
apiVersion: getambassador.io/v2
kind: Module
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: "ambassador"
  namespace: "{{ .Release.Namespace }}" 
spec:
  #ambassador_id: [ "ambassador1" ]
  config:
  {{- .Values.ambassador.module.config.custom | nindent 4 }}
  {{- if not .Values.global.web.ssl.letsencrypt.enabled -}}
  {{- .Values.ambassador.module.config.ipWhitelist | nindent 4 }}
  {{- end -}}
{{- end -}}