{{- if (index $.Values.global "emissary-ingress" "enabled") -}}
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: "{{ .Release.Name }}-alertmanager-mapping"
  namespace: "{{ .Release.Namespace }}"
spec:
  #ambassador_id: [ "ambassador1","ambassador2" ]
  add_response_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
  host: {{ .Values.global.externalDomain }}
  prefix: "/alertmanager/"
  service: "http://{{ .Release.Name }}-prometheus-alertmanager:9093"
  timeout_ms: 90000
{{- end -}}