apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: "{{ .Release.Name }}-alertmanager-mapping"
  namespace: "{{ .Release.Namespce }}"
spec:
  add_response_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
  host: monitor-sandbox.valamis.io
  prefix: "/alertmanager/"
  service: "http://{{ .Release.Name }}-prometheus-alertmanager:9093"
  timeout_ms: 90000