{{- if and (index $.Values.global "kube-prometheus-stack" "enabled") ($.Values.customResources.prometheusCustomAlertRules.create) -}}
{{ $releasename := .Release.Name }}
{{ $releasenamespace := .Release.Namespace }}
{{ range $ruleName, $_ := $.Values.customResources.prometheusCustomAlertRules.rules }}
{{- if . -}}
{{- $ruleFileName := printf "files/alert-rules/%s.yaml" $ruleName -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: "{{ $releasename }}"
    meta.helm.sh/release-namespace: "{{ $releasenamespace }}"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    role: prometheus-alerting-rules
    release: "{{ $releasename }}"
  name: "{{ $releasename }}-alert-rules-{{ $ruleFileName | base | trimSuffix ".yaml" }}"
  namespace: "{{ $releasenamespace }}"
spec:
{{ $.Files.Get $ruleFileName | indent 2 }}
---
{{- end -}}
{{- end -}}
{{- end -}}
