{{- if (index $.Values.global "emissary-ingress" "enabled") -}}
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ $.Release.Name }}-http-listener
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF
{{- if $.Values.global.web.ssl.enabled -}}
{{- $secretName := printf "%s-secret" ($.Values.global.externalDomain | adler32sum) }}
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ $.Release.Name }}-https-listener
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: {{ $.Values.global.externalDomain }}-host
spec:
  hostname: {{ $.Values.global.externalDomain }}
  tlsSecret:
    name: {{ $secretName }}
  ssl:
    alpn_protocols: h2,http/1.1
    min_tls_version: v1.2
    max_tls_version: v1.3
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: {{ $.Values.global.externalDomain }}-host-acme
spec:
  hostname: {{ $.Values.global.externalDomain }}
{{- if $.Values.global.web.ssl.letsencrypt.enabled -}}
{{- $issuer := printf "%s-issuer" ($.Values.global.externalDomain | adler32sum) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $issuer }}
  namespace: {{ $.Release.Namespace }}
spec:
  acme:
    server: "{{ .Values.global.web.ssl.letsencrypt.server }}"
    preferredChain: "{{ .Values.global.web.ssl.letsencrypt.preferredRootChain }}"
    email: {{ tpl $.Values.global.web.ssl.letsencrypt.issuerEmail . }}
    privateKeySecretRef:
      name: {{ $issuer }}
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $.Values.global.externalDomain | adler32sum }}-crt-svc
spec:
  host: {{ $.Values.global.externalDomain }}
  prefix: "/.well-known/acme-challenge/"
  rewrite: ""
  service: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $.Values.global.externalDomain | adler32sum }}-crt-svc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-{{ $.Values.global.externalDomain | adler32sum }}-crt-svc
spec:
  ports:
    - port: 80
      targetPort: 8089
  selector:
    acme.cert-manager.io/http-domain: "{{ $.Values.global.externalDomain | adler32sum }}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ $secretName }}
  issuerRef:
    name: {{ $issuer }}
    kind: Issuer
  commonName: {{ $.Values.global.externalDomain }}
  dnsNames:
    - {{ $.Values.global.externalDomain }}
{{- else if and .Values.global.web.ssl.externalSecret.enabled (eq .Values.global.web.ssl.externalSecret.backendType "azureKeyVault") }}
{{- if .Values.global.web.ssl.externalSecret.esoMigrated }}
---
# Adding cert and key into secret from Key vault. (ESO)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}-eso
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ default "default" .Values.global.web.ssl.externalSecret.ClusterSecretStore }}
  target:
    creationPolicy: Owner
    name: {{ $secretName }}
    template:
      type: kubernetes.io/tls
  data:
    - remoteRef:
        key: {{ .Values.global.externalDomain | replace "." "-" }}-crt
      secretKey: tls.crt
    - remoteRef:
        key: {{ .Values.global.externalDomain | replace "." "-" }}-key
      secretKey: tls.key
{{- else }}
---
# Adding cert and key into secret from Key vault. (KES)
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  backendType: {{ .Values.global.web.ssl.externalSecret.backendType }}
  template:
    type: kubernetes.io/tls
  keyVaultName: {{ .Values.global.web.ssl.externalSecret.keyVaultName }}
  data:
    - name: tls.crt
      key: {{ .Values.global.externalDomain | replace "." "-" }}-crt
      isBinary: false
    - name: tls.key
      key: {{ .Values.global.externalDomain | replace "." "-" }}-key
      isBinary: false
{{- end }}
{{- else }}
---
# Secret with self-signed crt and key.
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.global.web.ssl.default.selfsigned.cert | b64enc }}
  tls.key: |
    {{ .Values.global.web.ssl.default.selfsigned.key | b64enc }}
{{- end -}}
{{- end -}}
{{- end -}}